Notes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('yournotes/', include('YourNotes.urls'))
]

YourNotes/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'YourNotes'
urlpatterns = [
    path('', views.login_view, name="login_screen"),
	path('login', views.loginprocess_view, name="login_process"),
	path('register', views.register_view, name="register"),
	path('registration', views.registerprocess_view, name="register_process"),
	path('?P<username>/notelist', views.showlist_view, name="notelist"),
	path('?P<username>/addnote', views.createNote_view, name="addnote"),
	path('?P<username>/?P<title>/deletenote', views.deleteNote_view, name="deletenote"),
	path('?P<username>/?P<title>/updatenote', views.updateNote_view, name="updatenote"),
	path('?P<username>/?P<title>/updatenoteprocess', views.updateNoteprocess_view, name="updatenoteprocess"),
	path('?P<username>/?P<title>/notedetails', views.noteDetails_view, name="notedetails"),
	path('logout', views.logout_view, name="logout")
]

YourNotes/models.py
from django.db import models
import datetime	

# Create your models here.

class User(models.Model):
	actual_name = models.CharField(max_length=30)
	user_name = models.CharField(max_length=20)
	user_password = models.CharField(max_length=50)
	user_email = models.EmailField(
    	verbose_name ='email address',
        max_length=50,
        unique=True,
    )
	active = models.BooleanField(default=True)

class userNotes(models.Model):
	note_title =  models.CharField(max_length=50)
	note_detail = models.CharField(max_length=200)
	due_date = models.DateField()
	created_date = models.DateField(default=datetime.date.today, blank=True) 
	high_imp = models.BooleanField(default=False)
	status = models.BooleanField(default=False)
	usr_name = models.ForeignKey(User, on_delete=models.CASCADE)
	
	
	

YourNotes/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
import datetime
from django.contrib.auth import login, logout, authenticate
from YourNotes.models import User, userNotes

# Create your views here.

def login_view(request):
	if request.session.has_key('username'):
		username = request.session['username']
		return HttpResponseRedirect(reverse('YourNotes:notelist', args=(username,)))
	else:
		return render(request, 'YourNotes/login1.html')

def loginprocess_view(request):
	if request.method == "POST":
		try:
			username = request.POST['username']
			password = request.POST['password']
		
			check_user = User.objects.get(user_name=username)
		except User.DoesNotExist:
			context={
				"error":"Please register yourself:)"
			}
			return render(request, 'YourNotes/login1.html', context)                            
		else:
			if check_user.user_password == password:
				#return HttpResponse("Successfully logged in:)");					#call showlist_view()
				#showlist_view(request, username);
				request.session['username'] = username
				return HttpResponseRedirect(reverse('YourNotes:notelist', args=(username,)))
			else:
				context={
					"error":"Please provide valid credentials!"
				}
				return render(request, 'YourNotes/login1.html', context)	
			#user = authenticate(request, username=username, password=password)
		#if user:
		#	login(request, user)
		#	return HttpResponse("Successfully logged in:)");
		#else:
		#	context={
		#		"error":"Please provide valid credentials!"
		#	}
		#	return render(request, 'YourNotes/login1.html', context)	
	else:
		return render(request, 'YourNotes/login1.html')

def logout_view(request):
	pass

def register_view(request):
	return render(request, 'YourNotes/registration.html')

def registerprocess_view(request):
	#return render(request, 'YourNotes/registration.html')
	if request.method == 'POST':
		try:
			username = request.POST['username']
			user_object = User.objects.get(user_name=username)
		except User.DoesNotExist:
			name = request.POST['name']
			password = request.POST['password']
			email = request.POST['email']
			new_user = User(actual_name=name, user_name=username, user_password=password, user_email = email)
			new_user.save()
			#return HttpResponse("Registration successfull:)");                                    #call showlist_view()
			#showlist_view(request, username);
			equest.session['username'] = username
			return HttpResponseRedirect(reverse('YourNotes:notelist', args=(username,)))
		else:
			context={
				"error":"Username allready exist. Please try something else!"
			}
			return render(request, 'YourNotes/registration.html', context)	
	else:
		return render(request, 'YourNotes/registration.html')
	
def showlist_view(request, username):
	#return HttpResponse("Listing your notes shortly..."+" "+username);
	#recent_note = userNotes.objects.filter(usr_name=username)
	user_object = User.objects.get(user_name=username)
	recent_note = user_object.usernotes_set.all()
	context = {
		'note_list':recent_note,
		'username':username,
		'current_date':datetime.date.today
	}
	return render(request, 'YourNotes/note_list.html', context)

def createNote_view(request, username):
	if request.method != 'POST':
		return render(request, 'YourNotes/new_note.html')
	else:
		title = request.POST['title']
		description = request.POST['description']
		due_date = request.POST['due_date']
		importance = request.POST.get('importance')
		if importance == 'on':
			imp = 1
		else:
			imp = 0
		#importance = request.POST['importance']
		q = User.objects.get(user_name=username)
		new_note = q.usernotes_set.create(note_title=title, note_detail=description, due_date=due_date, high_imp=imp)
		return render(request, 'YourNotes/new_note.html')

def deleteNote_view(request, username, title):
	select_user = User.objects.get(user_name=username)
	delete_note = select_user.usernotes_set.get(note_title=title)
	delete_note.delete()
	
	user_object = User.objects.get(user_name=username)
	recent_note = user_object.usernotes_set.all()
	
	context={
		"message":"Note removed successfully:)",
		'note_list':recent_note,
		'username':username,
		'current_date':datetime.date.today
		
	}
	return render(request, 'YourNotes/note_list.html', context)

def updateNote_view(request, username, title):
	user_object = User.objects.get(user_name=username)
	recent_note = user_object.usernotes_set.get(note_title = title)
	#print(recent_note.high_imp)
	#date = recent_note.due_date.strftime("%yyyy-%MM-%dd")
	#parsed_date = datetime.datetime.strptime(str(recent_note.due_date), "%Y-%m-%d")
	context = {
		'recent_note':recent_note,
		'username':username
	}
	return render(request, 'YourNotes/update_note.html', context)

def updateNoteprocess_view(request, username, title):
	if request.method != 'POST':
		return render(request, 'YourNotes/new_note.html')
	else:
		description = request.POST['description']
		due_date = request.POST['due_date']
		importance = request.POST.get('importance')
		status = request.POST.get('status')
		if importance == 'on':
			imp = 1
		else:
			imp = 0
		if status == 'on':
			state = 1
		else:
			state = 0	
		#importance = request.POST['importance']
		q = User.objects.get(user_name=username)
		new_note = q.usernotes_set.get(note_title=title)
		new_note.note_detail = description
		new_note.due_date = due_date
		new_note.high_imp = imp
		new_note.status = state
		new_note.save()
		#return render(request, 'YourNotes/note_list.html')
		return HttpResponseRedirect(reverse('YourNotes:notelist', args=(username,)))

	
def noteDetails_view(request, username, title):
	user_object = User.objects.get(user_name=username)
	recent_note = user_object.usernotes_set.get(note_title = title)
	context = {
		'recent_note':recent_note,
		'username':username
	}
	return render(request, 'YourNotes/note_details.html', context)

def logout_view(request):
	try:
		del request.session['username']
	except:
		pass
	return HttpResponse("<h1>You are logged out.</h1>")

YourNotes/templates/YourNotes/header.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">YourNotes</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Page 1-1</a></li>
          <li><a href="#">Page 1-2</a></li>
          <li><a href="#">Page 1-3</a></li>
        </ul>
      </li>
      <li><a href="#">Page 2</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <!--<li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>-->
      <li><a href="{% url 'YourNotes:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
    </ul>
  </div>
</nav>
  

</body>
</html>

YourNotes/templates/YourNotes/header1.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">YourNotes</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Page 1-1</a></li>
          <li><a href="#">Page 1-2</a></li>
          <li><a href="#">Page 1-3</a></li>
        </ul>
      </li>
      <li><a href="#">Page 2</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'YourNotes:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <!--<li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>-->
    </ul>
  </div>
</nav>
  

</body>
</html>

YourNotes/templates/YourNotes/login1.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Login Form</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
<style type="text/css">
	.login-form {
		width: 340px;
    	margin: 50px auto;
	}
    .login-form form {
    	margin-bottom: 15px;
        background: #f7f7f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .login-form h2 {
        margin: 0 0 15px;
    }
    .form-control, .btn {
        min-height: 38px;
        border-radius: 2px;
    }
    .btn {        
        font-size: 15px;
        font-weight: bold;
    }
</style>
</head>
<body>
	{% include 'YourNotes/header1.html' %}
<div class="login-form">
    <form action="{% url 'YourNotes:login_process' %}" method="post">
		{% csrf_token %}
        <h2 class="text-center">Log in</h2>       
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Username" name="username" required="required">
        </div>
        <div class="form-group">
            <input type="password" class="form-control" placeholder="Password" name="password" required="required">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
        </div>
		<p class="text-danger">{{error}}</p>
        <div class="clearfix">
            <!--<label class="pull-left checkbox-inline"><input type="checkbox" name="remember"> Remember me</label>
            <a href="#" class="pull-right">Forgot Password?</a>-->
			<a href="#" class="text-center">Forgot Password?</a>
        </div>        
    </form>
    <p class="text-center"><a href="{% url 'YourNotes:register' %}">Create an Account</a></p>
</div>
</body>
</html>                                		                            

YourNotes/templates/YourNotes/new_note.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>New Note</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
<style type="text/css">
	.login-form {
		width: 340px;
    	margin: 50px auto;
	}
    .login-form form {
    	margin-bottom: 15px;
        background: #f7f7f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .login-form h2 {
        margin: 0 0 15px;
    }
    .form-control, .btn {
        min-height: 38px;
        border-radius: 2px;
    }
    .btn {        
        font-size: 15px;
        font-weight: bold;
    }
</style>
</head>
<body>
{% include 'YourNotes/header.html' %}	
<div class="login-form">
    <form action="" method="post">
		{% csrf_token %}
        <h2 class="text-center">New Note</h2>
		<div class="form-group">
            <input type="text" class="form-control" placeholder="Note Title" name="title" required="required">
        </div>
        <div class="form-group">
            <textarea class="form-control" placeholder="Desribe your Note" name="description"></textarea>
        </div>
        <div class="form-group">
            <input type="date" class="form-control" placeholder="Due Date" name="due_date" required="required">
        </div>
		<div class="form-group">
			<div class="clearfix">
            	<label class="pull-left checkbox-inline"><input type="checkbox" name="importance"> Very Important?</label>
			</div>
		</div>	
		<!--<div class="form-group">
            <input type="email" class="form-control" placeholder="Email" name="email" required="required">
        </div>-->
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Add New Note</button>
        </div>
		<p>{{error}}</p>
        <!--<div class="clearfix">
            <label class="pull-left checkbox-inline"><input type="checkbox"> Remember me</label>
            <a href="#" class="pull-right">Forgot Password?</a>
        </div>        
    </form>
    <p class="text-center"><a href="#">Create an Account</a></p>-->
</div>
</body>
</html>                                		                            

YourNotes/templates/YourNotes/note_details.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Update Note</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
<style type="text/css">
	.login-form {
		width: 340px;
    	margin: 50px auto;
	}
    .login-form form {
    	margin-bottom: 15px;
        background: #f7f7f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .login-form h2 {
        margin: 0 0 15px;
    }
    .form-control, .btn {
        min-height: 38px;
        border-radius: 2px;
    }
    .btn {        
        font-size: 15px;
        font-weight: bold;
    }
</style>
</head>
<body>
	{% include 'YourNotes/header.html' %}	
<div class="login-form">
    <form action="{% url 'YourNotes:updatenoteprocess' username recent_note.note_title %}" method="post">
		{% csrf_token %}
        <h2 class="text-center">Note Details</h2>
		<div class="form-group">
            <input type="text" class="form-control" placeholder="Note Title" value={{recent_note.note_title}} name="title" readonly>
        </div>
        <div class="form-group">
           <textarea class="form-control" placeholder="Desribe your Note" name="description" readonly>{{recent_note.note_detail}}</textarea>
        </div>
        <div class="form-group">
            <input type="date" class="form-control" placeholder="Due Date" value={{recent_note.due_date|date:"Y-m-d"}} name="due_date" readonly>
        </div>
		<div class="form-group">
			<div class="clearfix">
				{% if recent_note.high_imp == False %}
            	<label class="pull-left checkbox-inline"><input type="checkbox" name="importance" readonly/> Very Important?</label>
				{% else %}
				<label class="pull-left checkbox-inline"><input type="checkbox" name="importance"  readonly checked/> Very Important?</label>
				{% endif %}
			</div>
		</div>
		<div class="form-group">
			<div class="clearfix">
				{% if recent_note.status == False %}
            	<label class="pull-left checkbox-inline"><input type="checkbox" name="status" readonly/> Completed</label>
				{% else %}
				<label class="pull-left checkbox-inline"><input type="checkbox" name="status" readonly checked/> Completed</label>
				{% endif %}
			</div>
		</div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Back</button>
        </div>
		<p>{{error}}</p>
        <!--<div class="clearfix">
            <label class="pull-left checkbox-inline"><input type="checkbox"> Remember me</label>
            <a href="#" class="pull-right">Forgot Password?</a>
        </div>        
    </form>
    <p class="text-center"><a href="#">Create an Account</a></p>-->
</div>
</body>
</html>                                		                            

YourNotes/templates/YourNotes/note_list.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Note List</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
<style type="text/css">
	.login-form {
		width: 340px;
    	margin: 50px auto;
	}
    .login-form form {
    	margin-bottom: 15px;
        background: #f7f7f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .login-form h2 {
        margin: 0 0 15px;
    }
    .form-control, .btn {
        min-height: 38px;
        border-radius: 2px;
    }
    .btn {        
        font-size: 15px;
        font-weight: bold;
    }
</style>
<head>
<body>
	

{% include 'YourNotes/header.html' %}	
	
<div class="container">
  <h2>Recent Notes</h2>
  <p>Please select filters to get customized list:)</p>     
	<p class="text-success">{{message}}</p>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Due Date</th>
        <th>Value Status</th>
      </tr>
    </thead>
    <tbody>
	{% for note in note_list %}
		{% if note.status == False %}
      <tr>
        <td>{{note.note_title}}</td>
		  {% if current_date > note.due_date %}
        <td class="text-danger">{{note.due_date}}</td>
		  {% else %}
		  <td>{{note.due_date}}</td>
		  {% endif %}
		  {% if note.high_imp == False %}
        <td>Normal Task</td>
		  {% else %}
		 <td>Important Task</td>
		 {% endif %}
		  <td>
			  <button class="btn btn-primary btn-block" onclick="location.href='{% url 'YourNotes:notedetails' username note.note_title %}'">
            Details
        </button>	
		  </td>
		  <td>
			  <button class="btn btn-primary btn-block" onclick="location.href='{% url 'YourNotes:updatenote' username note.note_title %}'">
            Update
        </button>	
		  </td>
		  <td>
			  <button class="btn btn-primary btn-block" onclick="location.href='{% url 'YourNotes:deletenote' username note.note_title %}'">
            Delete
        </button>	
		  </td>
      </tr>
		{% endif %}
	{% endfor %}	
    </tbody>
  </table>
</div>
           <!--<button type="submit" class="btn btn-primary btn-block">Add New Note</button>-->
	  <!--<input type="button" class="btn btn-primary btn-block" value="Add New Note" onclick="{% url 'YourNotes:addnote' username %}" />-->
		<button class="btn btn-primary btn-block" onclick="location.href='{% url 'YourNotes:addnote' username %}'">
            Add New Note
        </button>																														
</div>
</body>
</html>                                		                            

YourNotes/templates/YourNotes/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Registration Form</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
</head>
<style type="text/css">
	.login-form {
		width: 340px;
    	margin: 50px auto;
	}
    .login-form form {
    	margin-bottom: 15px;
        background: #f7f7f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .login-form h2 {
        margin: 0 0 15px;
    }
    .form-control, .btn {
        min-height: 38px;
        border-radius: 2px;
    }
    .btn {        
        font-size: 15px;
        font-weight: bold;
    }
</style>

<body>
{% include 'YourNotes/header.html' %}	
<div class="login-form">
    <form action="{% url 'YourNotes:register_process' %}" method="post">
		{% csrf_token %}
        <h2 class="text-center">Registration</h2>
		<div class="form-group">
            <input type="text" class="form-control" placeholder="Name" name="name" required="required">
			<p>{{error}}</p>
        </div>
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Username" name="username" required="required">
        </div>
        <div class="form-group">
            <input type="password" class="form-control" placeholder="Password" name="password" required="required">
        </div>
		<div class="form-group">
            <input type="email" class="form-control" placeholder="Email" name="email" required="required">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Register</button>
        </div>
		<!--<p>{{error}}</p>
        <div class="clearfix">
            <label class="pull-left checkbox-inline"><input type="checkbox"> Remember me</label>
            <a href="#" class="pull-right">Forgot Password?</a>
        </div>        
    </form>
    <p class="text-center"><a href="#">Create an Account</a></p>-->
</div>
</body>
</html>                                		                            

YourNotes/templates/YourNotes/update_note.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Update Note</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
<style type="text/css">
	.login-form {
		width: 340px;
    	margin: 50px auto;
	}
    .login-form form {
    	margin-bottom: 15px;
        background: #f7f7f7;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
    .login-form h2 {
        margin: 0 0 15px;
    }
    .form-control, .btn {
        min-height: 38px;
        border-radius: 2px;
    }
    .btn {        
        font-size: 15px;
        font-weight: bold;
    }
</style>
</head>
<body>
	{% include 'YourNotes/header.html' %}	
<div class="login-form">
    <form action="{% url 'YourNotes:updatenoteprocess' username recent_note.note_title %}" method="post">
		{% csrf_token %}
        <h2 class="text-center">Update Note</h2>
		<div class="form-group">
            <input type="text" class="form-control" placeholder="Note Title" value={{recent_note.note_title}} name="title" readonly>
        </div>
        <div class="form-group">
           <textarea class="form-control" placeholder="Desribe your Note" name="description">{{recent_note.note_detail}}</textarea>
        </div>
        <div class="form-group">
            <input type="date" class="form-control" placeholder="Due Date" value={{recent_note.due_date|date:"Y-m-d"}} name="due_date" required="required">
        </div>
		<div class="form-group">
			<div class="clearfix">
				{% if recent_note.high_imp == False %}
            	<label class="pull-left checkbox-inline"><input type="checkbox" name="importance"> Very Important?</label>
				{% else %}
				<label class="pull-left checkbox-inline"><input type="checkbox" name="importance" checked/> Very Important?</label>
				{% endif %}
			</div>
		</div>
		<div class="form-group">
			<div class="clearfix">
				{% if recent_note.status == False %}
            	<label class="pull-left checkbox-inline"><input type="checkbox" name="status"> Completed</label>
				{% else %}
				<label class="pull-left checkbox-inline"><input type="checkbox" name="status" checked> Completed</label>
				{% endif %}
			</div>
		</div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Update</button>
        </div>
		<p>{{error}}</p>
        <!--<div class="clearfix">
            <label class="pull-left checkbox-inline"><input type="checkbox"> Remember me</label>
            <a href="#" class="pull-right">Forgot Password?</a>
        </div>        
    </form>
    <p class="text-center"><a href="#">Create an Account</a></p>-->
</div>
</body>
</html>                                		                            